### ISSUE TITLE
To-Do for Backend

### ISSUE THREAD

**Issue by yusuferdemnacar** [yusuferdemnacar/Social-Network-Analysis-on-Research#40]
There are a few tasks to be done regarding the backend of the project. These are
* [ ] Implementing queries in the analysis engine
* [ ] Creating a new neo4j database using docker to avoid limitations of auraDB
* [ ] Designing a system for supporting multiple separate graphs in the graph database
* [ ] Setting up CI/CD using GitHub Actions (optional)
* [ ] Reformatting the code in compliance with pep8
* [ ] Refactoring the code to get rid of unused parts

**Deadline:** 10.02.2023

**Comment by yusuferdemnacar** [comment]
> * [ ]  Creating a new neo4j database using docker to avoid limitations of auraDB

I have learned how to do this, the only thing left to to is to find a machine to host it.

**Comment by yusuferdemnacar** [comment]
> * reating a new neo4j database using docker to avoid limitations of auraDB

The new neo4j databases on an EC2 instance on Amazon AWS is online.

**Comment by yusuferdemnacar** [comment]
Due to performance issues, the AWS server for neo4j DB is moved to local for now. This does not affect the implementation.

**Comment by yusuferdemnacar** [comment]
With issue #52 being closed due to changes in #57, this issue is complete. The optional changes are not implemented.
